diff --git a/chrome/browser/ui/tabs/BUILD.gn b/chrome/browser/ui/tabs/BUILD.gn
index 6e5411be85..4d9fd15b2e 100644
--- a/chrome/browser/ui/tabs/BUILD.gn
+++ b/chrome/browser/ui/tabs/BUILD.gn
@@ -507,6 +507,8 @@ if (!is_android) {
       "//chrome/app/vector_icons",
       "//chrome/browser/actor",
       "//chrome/browser/actor/ui",
+      "//chrome/browser/browseros/core",
+      "//chrome/browser/browseros/core:prefs",
       "//chrome/browser/commerce",
       "//chrome/browser/content_settings:content_settings_factory",
       "//chrome/browser/contextual_cueing",
