diff --git a/chrome/browser/ui/bookmarks/BUILD.gn b/chrome/browser/ui/bookmarks/BUILD.gn
index 5f56941363..1f4d955207 100644
--- a/chrome/browser/ui/bookmarks/BUILD.gn
+++ b/chrome/browser/ui/bookmarks/BUILD.gn
@@ -63,6 +63,7 @@ source_set("impl") {
   deps = [
     ":bookmarks",
     "//chrome/app:command_ids",
+    "//chrome/browser/browseros/core",
     "//chrome/browser/prefs",
     "//chrome/browser/profiles:profile",
     "//chrome/browser/search",
