diff --git a/chrome/browser/ui/startup/BUILD.gn b/chrome/browser/ui/startup/BUILD.gn
index 015937d019..cb0d828dd6 100644
--- a/chrome/browser/ui/startup/BUILD.gn
+++ b/chrome/browser/ui/startup/BUILD.gn
@@ -190,6 +190,7 @@ source_set("impl") {
       "//base:i18n",
       "//build:branding_buildflags",
       "//build:buildflag_header_h",
+      "//chrome/browser/browseros/core",
       "//chrome/browser:global_features",
       "//chrome/browser:shell_integration",
       "//chrome/browser/app_mode",
