diff --git a/chrome/browser/ui/BUILD.gn b/chrome/browser/ui/BUILD.gn
index dac5e9152b..c2645cafbf 100644
--- a/chrome/browser/ui/BUILD.gn
+++ b/chrome/browser/ui/BUILD.gn
@@ -282,6 +282,7 @@ static_library("ui") {
     "//chrome/browser/banners",
     "//chrome/browser/bitmap_fetcher",
     "//chrome/browser/breadcrumbs",
+    "//chrome/browser/browseros/core",
     "//chrome/browser/commerce",
     "//chrome/browser/complex_tasks",
     "//chrome/browser/content_settings",
@@ -1289,6 +1290,8 @@ static_library("ui") {
       "webui/settings/search_engines_handler.h",
       "webui/settings/security_settings_provider.cc",
       "webui/settings/security_settings_provider.h",
+      "webui/settings/browseros_metrics_handler.cc",
+      "webui/settings/browseros_metrics_handler.h",
       "webui/settings/settings_clear_browsing_data_handler.cc",
       "webui/settings/settings_clear_browsing_data_handler.h",
       "webui/settings/settings_localized_strings_privacy_sandbox_provider.cc",
@@ -3230,6 +3233,8 @@ static_library("ui") {
       "views/frame/immersive_mode_overlay_views_mac.mm",
       "views/tab_contents/chrome_web_contents_view_delegate_views_mac.h",
       "views/tab_contents/chrome_web_contents_view_delegate_views_mac.mm",
+      "webui/help/sparkle_version_updater_mac.h",
+      "webui/help/sparkle_version_updater_mac.mm",
       "webui/help/version_updater_mac.mm",
       "webui/settings/mac_system_settings_handler.cc",
       "webui/settings/mac_system_settings_handler.h",
